// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuALbS5TpU1sR0zLIOKvZZmm-5_L8FeBg',
    appId: '1:212650628589:web:621c670556a61351ac43e4',
    messagingSenderId: '212650628589',
    projectId: 'music-app-d886c',
    authDomain: 'music-app-d886c.firebaseapp.com',
    storageBucket: 'music-app-d886c.appspot.com',
    measurementId: 'G-XTP1E61WVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIByyrMuk6HD1iBj__YCEXkdz4CkosEmo',
    appId: '1:212650628589:android:aee5e28491172fa9ac43e4',
    messagingSenderId: '212650628589',
    projectId: 'music-app-d886c',
    storageBucket: 'music-app-d886c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo9m1DPGBvdPdTyEZaIjji5ihOrOeibkw',
    appId: '1:212650628589:ios:9e978eba6866fe18ac43e4',
    messagingSenderId: '212650628589',
    projectId: 'music-app-d886c',
    storageBucket: 'music-app-d886c.appspot.com',
    iosClientId: '212650628589-l5d4rje03kvql773m90naophvuerjhec.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.musicApp',
  );
}
